"""Build the lab notebooks from their jupytext sources (one way: never edit the .ipynb).

For each notebook in _variables.yml `modules.*.notebooks` whose source exists:

  labs/src/NN-slug.py  ->  labs/python/NN-slug.ipynb   (kernel python3)
  labs/src/NN-slug.R   ->  labs/r/NN-slug.ipynb        (kernel ir)

The generator writes five cells around the source's own cells (CONTRIBUTING.md):
header (title, Colab badge at repo.ref, day, minutes, goals, stack), install (runtime
detection and pinned installs), harness (WORKED_EXAMPLE, QUICK and the `workshop` object,
with the notebook's content_sha and deps_sha), record (summary and run record) and footer.
It marks solution cells as folded (`cellView: form`, `jupyter.source_hidden`), sets the
kernelspec, strips outputs and gives every cell a stable id. Running it twice changes
nothing.

Run:   python scripts/gen_notebooks.py           write the notebooks
       python scripts/gen_notebooks.py --check   exit 1 if any notebook would change
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path

import jupytext
import nbformat

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common  # noqa: E402
from common import (  # noqa: E402
    FOOTER_ID,
    HARNESS_ID,
    HEADER_ID,
    INSTALL_ID,
    KERNELS,
    RECORD_ID,
    ROOT,
)

BADGE = "https://colab.research.google.com/assets/colab-badge.svg"
NOTICE = (
    "<!-- GENERATED by scripts/gen_notebooks.py from _variables.yml. Do not edit this cell. -->"
)
CODE_NOTICE = "# Generated by scripts/gen_notebooks.py from _variables.yml: do not edit this cell."
LANGUAGE_NAMES = {"python": "Python", "r": "R"}


# ---- reading a source --------------------------------------------------------------------


def read_source(entry: dict) -> list:
    """The source's cells as nbformat cells: tags kept, everything else normalized."""
    fmt = KERNELS[entry["kernel"]]["fmt"]
    nb = jupytext.read(ROOT / entry["source"], fmt=fmt)
    cells = []
    for cell in nb.cells:
        source = cell.source.strip("\n").rstrip()
        if not source.strip():
            continue
        tags = list(cell.metadata.get("tags", []))
        if cell.cell_type == "markdown":
            new = nbformat.v4.new_markdown_cell(source)
        else:
            new = nbformat.v4.new_code_cell(source)
        new.metadata = nbformat.NotebookNode({})
        if tags:
            new.metadata["tags"] = tags
        if "solution" in tags:
            new.metadata["cellView"] = "form"
            new.metadata["jupyter"] = {"source_hidden": True}
        cells.append(new)
    for i, cell in enumerate(cells):
        cell["id"] = f"cell-{i:03d}"
    return cells


def exercises_python(cells: list) -> dict:
    """{n: (names...)} from @workshop.solution(n) and workshop.solution_value(n, "name", ...)."""
    out: dict = {}
    for cell in cells:
        if cell.cell_type != "code" or "solution" not in cell.metadata.get("tags", []):
            continue
        try:
            tree = ast.parse(cell.source)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                for dec in node.decorator_list:
                    if (
                        isinstance(dec, ast.Call)
                        and isinstance(dec.func, ast.Attribute)
                        and dec.func.attr == "solution"
                        and isinstance(dec.func.value, ast.Name)
                        and dec.func.value.id == "workshop"
                        and dec.args
                        and isinstance(dec.args[0], ast.Constant)
                    ):
                        out.setdefault(dec.args[0].value, []).append(node.name)
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "solution_value"
                and len(node.args) >= 2
                and isinstance(node.args[0], ast.Constant)
                and isinstance(node.args[1], ast.Constant)
            ):
                out.setdefault(node.args[0].value, []).append(node.args[1].value)
    ordered = sorted(out.items(), key=lambda kv: kv[0])
    return {n: tuple(dict.fromkeys(names)) for n, names in ordered}


R_SOLUTION = re.compile(r"^\s*solution\(\s*(\d+)\s*,\s*[\"']([^\"']+)[\"']", re.M)


def exercises_r(cells: list) -> dict:
    out: dict = {}
    for cell in cells:
        if cell.cell_type != "code" or "solution" not in cell.metadata.get("tags", []):
            continue
        for n, name in R_SOLUTION.findall(cell.source):
            out.setdefault(int(n), []).append(name)
    return {n: tuple(dict.fromkeys(names)) for n, names in sorted(out.items())}


# ---- the generated cells -----------------------------------------------------------------


def colab_url(v: dict, path: str) -> str:
    return f"{v['repo']['colab_base']}/{v['repo']['ref']}/{path}"


def stack(v: dict, entry: dict) -> str:
    lang = LANGUAGE_NAMES[entry["language"]]
    version = v["environment"]["python" if entry["language"] == "python" else "r"]
    names = list(entry["install"])
    return ", ".join([f"{lang} {version}", *names])


def header_source(v: dict, entry: dict) -> str:
    m = v["modules"][entry["module"]]
    day = v["days"][m["day"]]
    lab = m["minutes"]["lab"]
    when = day["label"]
    optional = " (optional pre-work)" if m.get("optional") else ""
    lines = [
        NOTICE,
        f"# Module {entry['n']} · {m['title']}",
        "",
        f"[![Open in Colab]({BADGE})]({colab_url(v, entry['path'])})",
        "",
        f"**{v['workshop']['title']}** · {when} · {LANGUAGE_NAMES[entry['language']]}"
        f" · {lab}-minute lab{optional}",
        "",
        m.get("summary") or "*Summary to be written.*",
        "",
    ]
    objectives = m.get("objectives") or []
    if objectives:
        lines += ["**By the end of this notebook you can:**", ""]
        lines += [f"- {o}" for o in objectives]
    else:
        lines.append("*Objectives to be written.*")
    lines += ["", f"**Stack:** {stack(v, entry)}"]
    if m.get("decision"):
        lines += ["", f"**The decision:** {m['decision']}"]
    lines += [
        "",
        "**How this notebook works.** Run the cells in order (Runtime > Run all is fine: it stops"
        " at the first exercise you have not written). Each exercise has a stub to complete, a"
        " folded solution, and a checkpoint that says whether your code passed.",
    ]
    return "\n".join(lines)


PY_INSTALL = """# @title Install and check the runtime { display-mode: "form" }
__NOTICE__
# On Colab or SageMaker: installs the workshop package `mktstats` at the pinned ref, and any
# package below whose version differs from the tested pins. Anywhere else: installs nothing.
import os as _os
import sys as _sys
import time as _time

_t0 = _time.time()
MKTSTATS_REF = "__REF__"
_REPO = "__REPO__"
_PINS = __PINS__
_CONSTRAINTS = "__CONSTRAINTS__"


def _mktstats_setup():
    import importlib
    import importlib.metadata as md
    import json
    import subprocess

    root = _os.environ.get("MKTSTATS_REPO_ROOT")
    if not root:  # a notebook opened inside a checkout of the repository
        here = _os.path.abspath(_os.getcwd())
        for _ in range(4):
            if _os.path.exists(_os.path.join(here, "src", "mktstats", "__init__.py")):
                root = here
                break
            here = _os.path.dirname(here)
    if root:  # local or CI: use the checkout, install nothing
        src = _os.path.join(root, "src")
        if src not in _sys.path:
            _sys.path.insert(0, src)
        return
    hosted = (
        bool(_os.environ.get("COLAB_RELEASE_TAG"))
        or "google.colab" in _sys.modules
        or bool(_os.environ.get("SAGEMAKER_APP_TYPE") or _os.environ.get("SAGEMAKER_SPACE_NAME"))
        or _os.path.exists("/opt/ml/metadata/resource-metadata.json")
    )
    if not hosted:
        return
    try:
        info = json.loads(md.distribution("mktstats").read_text("direct_url.json") or "{}")
        have = info.get("vcs_info", {}).get("commit_id")
    except md.PackageNotFoundError:
        have = None
    want = MKTSTATS_REF if len(MKTSTATS_REF) == 40 else None
    if want is None:
        try:
            out = subprocess.run(
                ["git", "ls-remote", _REPO, MKTSTATS_REF, MKTSTATS_REF + "^{}"],
                capture_output=True, text=True, timeout=30,
            )
            lines = [x.split() for x in out.stdout.splitlines() if x.strip()]
            peeled = [x[0] for x in lines if x[1].endswith("^{}")]
            want = (peeled or [x[0] for x in lines] or [None])[0]
        except Exception:
            want = None
    if have is not None and (want is None or have == want):
        return
    print(f"Installing mktstats from {_REPO} at {MKTSTATS_REF} ...")
    done = subprocess.run(
        [_sys.executable, "-m", "pip", "install", "-q", "--no-deps", "--force-reinstall",
         f"git+{_REPO}@{MKTSTATS_REF}"],
        capture_output=True, text=True,
    )
    if done.returncode != 0:
        tail = "\\n".join((done.stdout + done.stderr).strip().splitlines()[-10:])
        raise RuntimeError(f"Could not install mktstats:\\n{tail}\\nCheck the network and rerun.")
    for name in [m for m in _sys.modules if m == "mktstats" or m.startswith("mktstats.")]:
        del _sys.modules[name]
    importlib.invalidate_caches()


_mktstats_setup()
try:
    from mktstats import runtime as _runtime
except ModuleNotFoundError as _e:
    raise ModuleNotFoundError(
        "mktstats is not installed. In a checkout of the repository run `pip install -e .`,"
        " or set MKTSTATS_REPO_ROOT to the checkout."
    ) from _e
_runtime.ensure(_PINS, constraints_url=_CONSTRAINTS)
_os.environ["MKTSTATS_INSTALL_SECONDS"] = f"{_time.time() - _t0:.1f}"
_runtime.report()"""


R_INSTALL = """__NOTICE__
# On Colab: installs the R packages this lab needs (binaries from a dated Posit Public
# Package Manager snapshot) and sources the workshop helpers. Elsewhere: installs nothing.
.mkt_t0 <- Sys.time()
MKTSTATS_REF <- "__REF__"
options(mktstats.ref = MKTSTATS_REF, mktstats.raw = "__RAW__")
local({
  cran <- __CRAN__
  github <- __GITHUB__
  needs_gsl <- __GSL__
  root <- Sys.getenv("MKTSTATS_REPO_ROOT")
  hosted <- nzchar(Sys.getenv("COLAB_RELEASE_TAG")) || nzchar(Sys.getenv("SAGEMAKER_APP_TYPE")) ||
    file.exists("/opt/ml/metadata/resource-metadata.json")
  missing <- setdiff(c(cran, names(github)), rownames(installed.packages()))
  if (nzchar(root) || !hosted) {
    if (length(missing)) {
      warning("Not installed here: ", paste(missing, collapse = ", "),
              ". Use the workshop image (environment/Dockerfile) or install them.", call. = FALSE)
    }
    return(invisible())
  }
  options(
    repos = c(CRAN = "__P3M__"),
    HTTPUserAgent = sprintf(
      "R/%s R (%s)", getRversion(),
      paste(getRversion(), R.version["platform"], R.version["arch"], R.version["os"])
    ),
    timeout = 900
  )
  if (needs_gsl && !any(grepl("libgsl\\\\.so", system("ldconfig -p", intern = TRUE)))) {
    message("Installing the GSL system library ...")
    system("apt-get install -y -qq libgsl27 > /tmp/mktstats-apt.log 2>&1")
  }
  need <- setdiff(cran, rownames(installed.packages()))
  if (length(need)) install.packages(need)
  for (name in names(github)) {
    if (!name %in% rownames(installed.packages())) {
      archive <- sprintf("https://github.com/%s/archive/%s.tar.gz", github[[name]][1],
                         github[[name]][2])
      install.packages(archive, repos = NULL, type = "source")
    }
  }
  still <- setdiff(c(cran, names(github)), rownames(installed.packages()))
  if (length(still)) {
    stop("Could not install: ", paste(still, collapse = ", "),
         ". Rerun this cell; if it fails again, tell the instructor.", call. = FALSE)
  }
})
local({
  root <- Sys.getenv("MKTSTATS_REPO_ROOT")
  if (!nzchar(root)) {  # a notebook opened inside a checkout of the repository
    here <- normalizePath(getwd())
    for (i in 1:4) {
      if (file.exists(file.path(here, "R", "mktstats.R"))) { root <- here; break }
      here <- dirname(here)
    }
  }
  helpers <- if (nzchar(root)) file.path(root, "R", "mktstats.R") else
    sprintf("%s/%s/R/mktstats.R", getOption("mktstats.raw"), MKTSTATS_REF)
  source(helpers)
})
.mkt_secs <- as.numeric(difftime(Sys.time(), .mkt_t0, units = "secs"))
Sys.setenv(MKTSTATS_INSTALL_SECONDS = sprintf("%.1f", .mkt_secs))
.mkt_where <- Sys.getenv("COLAB_RELEASE_TAG")
cat("Runtime:", if (nzchar(.mkt_where)) paste("colab", .mkt_where) else "local", "·",
    R.version.string, "·", parallel::detectCores(), "CPUs · setup took",
    Sys.getenv("MKTSTATS_INSTALL_SECONDS"), "s\\n")"""


def _r_vector(items: list[str]) -> str:
    return "c(" + ", ".join(json.dumps(x) for x in items) + ")" if items else "character()"


def install_source(v: dict, entry: dict) -> str:
    repo = v["repo"]
    if entry["kernel"] == "python3":
        pins = common.python_pins(v, entry)
        return (
            PY_INSTALL.replace("__NOTICE__", CODE_NOTICE)
            .replace("__REF__", str(repo["ref"]))
            .replace("__REPO__", repo["url"])
            .replace("__PINS__", repr(pins))
            .replace("__CONSTRAINTS__", f"{repo['raw']}/{repo['ref']}/environment/requirements.txt")
        )
    r = common.r_install(v, entry)
    pairs = [
        f"{n} = c({json.dumps(rs)}, {json.dumps(sha)})" for n, (rs, sha) in r["github"].items()
    ]
    github = "list(" + ", ".join(pairs) + ")"
    return (
        R_INSTALL.replace("__NOTICE__", CODE_NOTICE)
        .replace("__REF__", str(repo["ref"]))
        .replace("__RAW__", repo["raw"])
        .replace("__CRAN__", _r_vector(r["cran"]))
        .replace("__GITHUB__", github)
        .replace("__GSL__", "TRUE" if r["gsl"] else "FALSE")
        .replace("__P3M__", r["p3m_url"])
    )


def harness_source(v: dict, entry: dict, body: list) -> str:
    content = common.sha_of_cells(body)
    deps = common.deps_sha(v, entry)
    ref = str(v["repo"]["ref"])
    if entry["kernel"] == "python3":
        exercises = exercises_python(body)
        return "\n".join(
            [
                '# @title Workshop harness: run this cell first { display-mode: "form" }',
                CODE_NOTICE,
                "# WORKED_EXAMPLE runs every reference solution in place of your code: a",
                "# complete worked example, not a sign that you did the exercises. QUICK shortens",
                "# long steps (sampling, data size).",
                'WORKED_EXAMPLE = False  # @param {type:"boolean"}',
                'QUICK = False  # @param {type:"boolean"}',
                "",
                "from mktstats import checks",
                "from mktstats.harness import start as _start",
                "",
                "workshop = _start(",
                f"    notebook={entry['id']!r},",
                f"    content_sha={content!r},",
                f"    deps_sha={deps!r},",
                f"    ref={ref!r},",
                f"    exercises={exercises!r},",
                ")",
            ]
        )
    exercises = exercises_r(body)
    items = ", ".join(f"`{n}` = {_r_vector(list(names))}" for n, names in sorted(exercises.items()))
    return "\n".join(
        [
            CODE_NOTICE,
            "# WORKED_EXAMPLE <- TRUE runs every reference solution in place of your code: a",
            "# complete worked example, not a sign that you did the exercises. QUICK <- TRUE",
            "# shortens long steps (sampling, data size).",
            "WORKED_EXAMPLE <- FALSE",
            "QUICK <- FALSE",
            ".ws_start(",
            f'  notebook = "{entry["id"]}",',
            f'  content_sha = "{content}",',
            f'  deps_sha = "{deps}",',
            f'  ref = "{ref}",',
            f"  exercises = list({items})",
            ")",
        ]
    )


def record_source(entry: dict) -> str:
    comment = (
        "# Which checkpoints passed, and on whose code; then the run record (also saved as"
        " run_record.json)."
    )
    if entry["kernel"] == "python3":
        return "\n".join([CODE_NOTICE, comment, "workshop.summary()", "workshop.run_record()"])
    return "\n".join([CODE_NOTICE, comment, "workshop_summary()", "run_record()"])


def next_notebook(v: dict, entry: dict) -> dict | None:
    """The next notebook in the same language, else the next one at all."""
    order = common.notebooks(v)
    later = [e for e in order if (e["n"], e["index"]) > (entry["n"], entry["index"])]
    same = [e for e in later if e["language"] == entry["language"]]
    return (same or later or [None])[0]


def footer_source(v: dict, entry: dict) -> str:
    site = v["repo"]["site"].rstrip("/")
    nxt = next_notebook(v, entry)
    lines = [NOTICE, "---"]
    if nxt is None:
        lines.append("**This is the last notebook.**")
    else:
        title = f"Module {nxt['n']} · {v['modules'][nxt['module']]['title']}"
        lang = LANGUAGE_NAMES[nxt["language"]]
        if (ROOT / nxt["path"]).exists():
            lines.append(f"**Next:** [{title}]({colab_url(v, nxt['path'])}) ({lang})")
        else:
            lines.append(f"**Next:** {title} ({lang}, in preparation)")
    lines += [
        "",
        f"[Workshop site]({site}/) · [All notebooks]({site}/notebooks.html) ·"
        f" [Source]({v['repo']['url']})",
        "",
        f"{v['workshop']['org']} · text CC BY 4.0, code MIT",
    ]
    return "\n".join(lines)


def _generated_markdown(cell_id: str, source: str):
    cell = nbformat.v4.new_markdown_cell(source)
    cell["id"] = cell_id
    cell["metadata"] = nbformat.NotebookNode({"tags": ["generated"]})
    return cell


def _generated_code(cell_id: str, source: str, form: bool):
    cell = nbformat.v4.new_code_cell(source)
    cell["id"] = cell_id
    cell["metadata"] = nbformat.NotebookNode({"tags": ["generated"]})
    if form:
        cell["metadata"]["cellView"] = "form"
    return cell


def build(v: dict, entry: dict):
    body = read_source(entry)
    python = entry["kernel"] == "python3"
    nb = nbformat.v4.new_notebook()
    nb.cells = [
        _generated_markdown(HEADER_ID, header_source(v, entry)),
        _generated_code(INSTALL_ID, install_source(v, entry), form=python),
        _generated_code(HARNESS_ID, harness_source(v, entry, body), form=python),
        *body,
        _generated_code(RECORD_ID, record_source(entry), form=False),
        _generated_markdown(FOOTER_ID, footer_source(v, entry)),
    ]
    k = KERNELS[entry["kernel"]]
    nb.metadata = nbformat.NotebookNode(
        {
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": dict(k["kernelspec"]),
            "language_info": dict(k["language_info"]),
        }
    )
    nb.nbformat, nb.nbformat_minor = 4, 5
    nbformat.validate(nb)
    return nb


def render(nb) -> str:
    text = nbformat.writes(nb, version=4)
    return text if text.endswith("\n") else text + "\n"


def check_layout(v: dict) -> list[str]:
    """Problems with the notebook list itself: sources in the wrong place, orphans."""
    problems = []
    declared = set()
    for e in common.notebooks(v):
        k = KERNELS[e["kernel"]]
        path, source = Path(e["path"]), Path(e["source"])
        declared.add(e["path"])
        if path.parent != Path("labs") / k["dir"] or path.suffix != ".ipynb":
            problems.append(f"{e['path']}: a {e['kernel']} notebook belongs in labs/{k['dir']}/")
        if source.parent != Path("labs/src") or source.suffix != k["ext"]:
            problems.append(f"{e['source']}: a {e['kernel']} source is labs/src/*{k['ext']}")
        if path.stem != source.stem:
            problems.append(f"{e['path']}: its source {e['source']} has another name")
    for d in ("python", "r"):
        for p in sorted((ROOT / "labs" / d).glob("*.ipynb")):
            rel = p.relative_to(ROOT).as_posix()
            if rel not in declared:
                problems.append(f"{rel}: not declared in _variables.yml modules.*.notebooks")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if anything would change")
    args = parser.parse_args(argv)
    v = common.load_variables()
    problems = check_layout(v)
    drift = []
    for entry in common.notebooks(v):
        if not (ROOT / entry["source"]).exists():
            if (ROOT / entry["path"]).exists():
                problems.append(f"{entry['path']}: its source {entry['source']} is missing")
            continue
        text = render(build(v, entry))
        out = ROOT / entry["path"]
        current = out.read_text(encoding="utf-8") if out.exists() else None
        if current == text:
            continue
        drift.append(entry["path"])
        if not args.check:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(text, encoding="utf-8")
            print(f"wrote {entry['path']}")
    if problems:
        print("\n".join(problems))
        return 1
    if args.check and drift:
        print("Generated notebooks are out of date (run python scripts/gen_notebooks.py):")
        print("\n".join(f"  {p}" for p in drift))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
