"""Write the generated Markdown the site includes, from _variables.yml, the lab sources and
the run records. Never edit the outputs by hand: change the inputs and rerun.

  _includes/facts.md              counts for the landing page
  _includes/days.md               the days as cards
  _includes/path.md               the numbered modules, by day
  _includes/schedule.md           one whole-day timetable per day, with clock times
  _includes/day-N.md              the module cards of day N
  _includes/run-N.md              the run sheet of day N (facilitators)
  _includes/module-NN.md          the header of module NN's page
  _includes/lab-NN.md             the lab steps of module NN, from its sources' headings
  _includes/notebooks.md          every notebook with its Colab link and measured time
  _includes/readiness.md          what has run where, per notebook (scripts/readiness.py)
  _includes/readiness-summary.md  one paragraph of the same
  _includes/install-times.md      measured install times by runtime
  _includes/sidebar.yml           the module sidebar (for _quarto.yml metadata-files)
  environment/VERSIONS.md         versions and the docs each pin was checked against
  README.md                       the region between <!-- BEGIN status --> and <!-- END status -->

Missing content keys (an empty summary, objectives or decision) render as "to be written",
never as an empty element. The readiness outputs judge age against the newest record's
date, never today's, so they change only when the repository does.

Run:   python scripts/gen_tables.py           write
       python scripts/gen_tables.py --check   exit 1 if any output would change
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common  # noqa: E402
import lab_steps  # noqa: E402
import readiness  # noqa: E402
import run_records  # noqa: E402

ROOT = common.ROOT
INCLUDES = ROOT / "_includes"
NOTICE = "<!-- GENERATED by scripts/gen_tables.py from {src}. Do not edit by hand. -->"
BADGE = "https://colab.research.google.com/assets/colab-badge.svg"
LANG = {"python": "Python", "r": "R"}
PART_NAMES = {"briefing": "Briefing", "lab": "Lab", "debrief": "Debrief"}
BLOCK_NAMES = {"warmup": "Warm-up", "wrapup": "Wrap-up", "break": "Break", "lunch": "Lunch"}
# Timetable classes (CONTRIBUTING.md): breaks and lunch are .slot-break; the whole-room
# warm-up and wrap-up share .slot-debrief; a hands-on clinic shares .slot-lab.
BLOCK_CLASS = {
    "warmup": "slot-debrief",
    "wrapup": "slot-debrief",
    "break": "slot-break",
    "lunch": "slot-break",
    "clinic": "slot-lab",
}
# A module whose lab is longer than this is a long hands-on block (the capstone): it is left
# out of the "minutes of briefing / lab" ranges on the landing page.
LONG_LAB = 120
TBW = "to be written"


# ---- reading _variables.yml ----------------------------------------------------------------


def modules(v: dict) -> list[tuple[str, dict]]:
    return sorted(v["modules"].items(), key=lambda kv: common.module_number(kv[0]))


def days(v: dict) -> list[tuple[str, dict]]:
    return sorted(v["days"].items(), key=lambda kv: int(kv[0][1:]))


def day_number(key: str) -> int:
    return int(key[1:])


def to_minutes(hhmm: str) -> int:
    return int(hhmm[:2]) * 60 + int(hhmm[3:5])


def clock(minutes: int) -> str:
    return f"{minutes // 60:02d}:{minutes % 60:02d}"


PARTS = ("briefing", "lab", "debrief")


def plan(v: dict, dkey: str) -> list[dict]:
    """The day's segments with clock times.

    A module block without `part` is the whole module: its briefing, lab and debrief, back
    to back (parts with 0 minutes are left out). A module block with `part:` is only that
    part, for `minutes:` (default: all of the part) with an optional `title:`, so a part
    can be split around lunch (part_problems() checks the pieces add up).
    """
    d = v["days"][dkey]
    if not d.get("blocks"):
        return []
    t = to_minutes(d.get("start", "09:00"))
    out = []
    for block in d["blocks"]:
        if block["kind"] == "module":
            m = v["modules"][block["id"]]
            part = block.get("part")
            parts = [part] if part else list(PARTS)
            for p in parts:
                default = int(m["minutes"].get(p, 0) or 0)
                minutes = int(block.get("minutes", default)) if part else default
                if minutes:
                    seg = {"kind": p, "module": block["id"], "start": t, "end": t + minutes}
                    if part and block.get("title"):
                        seg["title"] = block["title"]
                    out.append(seg)
                    t += minutes
        else:
            minutes = int(block["minutes"])
            title = block.get("title") or BLOCK_NAMES.get(block["kind"], block["kind"].title())
            out.append({"kind": block["kind"], "title": title, "start": t, "end": t + minutes})
            t += minutes
    return out


def part_problems(v: dict) -> list[str]:
    """Each scheduled module's segments must add up to its minutes, part by part; a module
    is scheduled either whole or in parts, on its own day; every day ends by 17:00."""
    problems = []
    for dkey, d in days(v):
        segs = plan(v, dkey)
        if segs and segs[-1]["end"] > to_minutes("17:00"):
            problems.append(f"{dkey} ends at {clock(segs[-1]['end'])}, after 17:00")
        if segs and segs[0]["start"] < to_minutes("09:00"):
            problems.append(f"{dkey} starts at {clock(segs[0]['start'])}, before 09:00")
        for b in d.get("blocks") or []:
            if b["kind"] == "module" and v["modules"][b["id"]]["day"] != dkey:
                problems.append(f"{dkey}: {b['id']} is scheduled here but its day is another")
    for key, m in modules(v):
        segs = [s for dk, _ in days(v) for s in plan(v, dk) if s.get("module") == key]
        if not segs:
            continue
        blocks = [
            b
            for _, d in days(v)
            for b in d.get("blocks") or []
            if b["kind"] == "module" and b["id"] == key
        ]
        whole = [b for b in blocks if not b.get("part")]
        if whole and len(blocks) > 1:
            problems.append(f"{key}: scheduled whole and in parts (or twice)")
        for p in PARTS:
            want = int(m["minutes"].get(p, 0) or 0)
            got = sum(s["end"] - s["start"] for s in segs if s["kind"] == p)
            if got != want:
                problems.append(f"{key}: its {p} segments add up to {got} minutes, not {want}")
    return problems


def span(segments: list[dict]) -> str:
    return f"{clock(segments[0]['start'])}–{clock(segments[-1]['end'])}" if segments else ""


def module_segments(v: dict, key: str) -> list[dict]:
    m = v["modules"][key]
    return [s for s in plan(v, m["day"]) if s.get("module") == key]


def module_clock(v: dict, key: str) -> str:
    """'09:15–11:00', or one range per stretch when a break splits the module:
    '11:30–12:25 · 13:25–14:40'."""
    ranges: list[list[int]] = []
    for s in module_segments(v, key):
        if ranges and ranges[-1][1] == s["start"]:
            ranges[-1][1] = s["end"]
        else:
            ranges.append([s["start"], s["end"]])
    return " · ".join(f"{clock(a)}–{clock(b)}" for a, b in ranges)


def part_times(v: dict, key: str) -> str:
    """'11:30 briefing · 13:25 lab · 14:20 debrief': when each part (or piece) starts."""
    return " · ".join(f"{clock(s['start'])} {s['kind']}" for s in module_segments(v, key))


def module_number(key: str) -> int:
    return common.module_number(key)


def day_modules(v: dict, dkey: str) -> list[str]:
    keys = [b["id"] for b in v["days"][dkey].get("blocks", []) if b["kind"] == "module"]
    if not keys:  # pre-work: modules assigned to the day, without blocks
        keys = [k for k, m in modules(v) if m["day"] == dkey]
    return list(dict.fromkeys(keys))


def teaching_days(v: dict) -> list[tuple[str, dict]]:
    return [(k, d) for k, d in days(v) if d.get("blocks")]


def minutes_text(m: dict) -> str:
    parts = [(p, int(m["minutes"].get(p, 0) or 0)) for p in ("briefing", "lab", "debrief")]
    parts = [(p, n) for p, n in parts if n]
    total = sum(n for _, n in parts)
    inner = ", ".join(f"{n} {p}" for p, n in parts)
    return f"{total} minutes ({inner})" if len(parts) > 1 else f"{total}-minute {parts[0][0]}"


def notebooks_of(v: dict, key: str) -> list[dict]:
    return [e for e in common.notebooks(v) if e["module"] == key]


def exists(entry: dict) -> bool:
    return (ROOT / entry["path"]).exists()


def colab_url(v: dict, entry: dict) -> str:
    return f"{v['repo']['colab_base']}/{v['repo']['ref']}/{entry['path']}"


def module_link(key: str, m: dict) -> str:
    return f"/modules/{m['slug']}.qmd"


def day_link(dkey: str) -> str:
    return f"/day-{day_number(dkey)}.qmd"


def text_or(value, fallback: str) -> str:
    value = (value or "").strip() if isinstance(value, str) else value
    return value if value else f"*{fallback[0].upper()}{fallback[1:]}.*"


def colab_buttons(v: dict, key: str) -> str:
    out = []
    for e in notebooks_of(v, key):
        lang = LANG[e["language"]]
        if exists(e):
            out.append(
                f"[Open the {lang} lab in Colab]({colab_url(v, e)}){{.btn-colab}} [{lang}]{{.chip}}"
            )
        else:
            out.append(f"[{lang} lab in preparation]{{.chip}}")
    return " ".join(out)


# ---- landing page ------------------------------------------------------------------------


def exercise_counts(v: dict) -> tuple[int, int]:
    """(exercises in the written notebooks, written notebooks)."""
    written = [e for e in common.notebooks(v) if exists(e)]
    return sum(len(lab_steps.exercises(e)) for e in written), len(written)


def range_text(values: list[int]) -> str:
    if not values:
        return "–"
    lo, hi = min(values), max(values)
    return str(lo) if lo == hi else f"{lo}–{hi}"


def facts(v: dict) -> str:
    entries = common.notebooks(v)
    taught = [(k, m) for k, m in modules(v) if not m.get("optional")]
    optional = [(k, m) for k, m in modules(v) if m.get("optional")]
    n_py = sum(e["language"] == "python" for e in entries)
    n_r = sum(e["language"] == "r" for e in entries)
    n_ex, written = exercise_counts(v)
    standard = [m for _, m in taught if 0 < m["minutes"]["lab"] <= LONG_LAB]
    mods = f"**{len(taught)}** modules" + (" + optional pre-work" if optional else "")
    notebooks = f"**{len(entries)}** lab notebooks ({n_py} Python, {n_r} R)"
    if written < len(entries):
        notebooks += f", {written} written so far"
    exercises = f"**{n_ex}** hands-on exercises" + (" so far" if written < len(entries) else "")
    items = [
        f"**{len(teaching_days(v))}** days",
        mods,
        notebooks,
        exercises,
        f"**{range_text([m['minutes']['briefing'] for m in standard])}** min briefings,"
        f" **{range_text([m['minutes']['lab'] for m in standard])}** min labs",
    ]
    return "::: {.facts}\n" + "\n".join(f"[{x}]{{.fact}}" for x in items) + "\n:::"


def days_cards(v: dict) -> str:
    out = ["::: {.day-grid}"]
    for dkey, d in days(v):
        keys = day_modules(v, dkey)
        nums = [module_number(k) for k in keys]
        if d.get("blocks"):
            link = day_link(dkey)
            what = f"Modules {nums[0]}–{nums[-1]}" if len(nums) > 1 else f"Module {nums[0]}"
            span_text = f"{what} · {span(plan(v, dkey))}"
        else:
            link = module_link(keys[0], v["modules"][keys[0]]) if keys else "/index.qmd"
            optional = all(v["modules"][k].get("optional") for k in keys)
            span_text = f"Module {', '.join(map(str, nums))}" + (", optional" if optional else "")
        out += [
            "::: {.day-card}",
            f"[{d['label']}]{{.eyebrow}}",
            "",
            f"[{d['title']}]({link}){{.day-card-title}}",
            "",
            f"[{d['question']}]{{.day-card-question}}",
            "",
            f"[{span_text}]{{.day-card-span}}",
            ":::",
        ]
    out.append(":::")
    return "\n".join(out)


def path(v: dict) -> str:
    out = ["::: {.path}"]
    for dkey, d in days(v):
        keys = day_modules(v, dkey)
        if not keys:
            continue
        label = f"{d['label']} · {d['title']}"
        label = (
            f"[{label}]({day_link(dkey)}){{.path-day-label}}"
            if d.get("blocks")
            else (f"[{label}]{{.path-day-label}}")
        )
        out += ["::: {.path-day}", label, ""]
        for key in keys:
            m = v["modules"][key]
            optional = bool(m.get("optional"))
            chip = " [Optional]{.chip}" if optional else ""
            out += [
                "::: {.path-step" + (" .path-step-optional" if optional else "") + "}",
                f"[{module_number(key)}]{{.path-num}}",
                "",
                "::: {.path-body}",
                f"[{m['title']}]({module_link(key, m)}){{.path-title}}{chip}",
                "",
                text_or(m.get("summary"), f"summary {TBW}"),
                ":::",
                ":::",
            ]
        out.append(":::")
    out.append(":::")
    return "\n".join(out)


# ---- schedule, day cards, run sheets ---------------------------------------------------------


def segment_cells(v: dict, s: dict) -> tuple[str, str]:
    """(session cell, module cell) for one timetable row."""
    if "module" in s:
        m = v["modules"][s["module"]]
        name = PART_NAMES[s["kind"]] + (f" · {s['title']}" if s.get("title") else "")
        title = f"[{module_number(s['module'])} · {m['title']}]({module_link(s['module'], m)})"
        return f"[{name}]{{.slot-{s['kind']}}}", title
    css = BLOCK_CLASS.get(s["kind"], "slot-break")
    return f"[{s['title']}]{{.{css}}}", ""


def schedule(v: dict) -> str:
    out = []
    for dkey, d in days(v):
        n = day_number(dkey)
        if not d.get("blocks"):
            keys = day_modules(v, dkey)
            mods = ", ".join(
                f"[Module {module_number(k)} · {v['modules'][k]['title']}]"
                f"({module_link(k, v['modules'][k])})"
                for k in keys
            )
            lab = sum(v["modules"][k]["minutes"]["lab"] for k in keys)
            out += [
                f"## {d['label']} · {d['title']} {{#day-{n}}}",
                "",
                f"*{d['question']}*",
                "",
                f"On your own, before the workshop: {mods} (about {lab} minutes).",
                "",
            ]
            continue
        segs = plan(v, dkey)
        rows = ["| Time | Session | Module |", "|---|---|---|"]
        linked = set()
        for s in segs:
            session, module = segment_cells(v, s)
            if "module" in s:
                if s["module"] in linked:  # the title is on the module's first row
                    module = f"Module {module_number(s['module'])}"
                linked.add(s["module"])
            rows.append(f"| {clock(s['start'])}–{clock(s['end'])} | {session} | {module} |")
        out += [
            f"## [{d['label']} · {d['title']}]({day_link(dkey)}) {{#day-{n}}}",
            "",
            f"*{d['question']}* {span(segs)}",
            "",
            "::: {.timetable}",
            "\n".join(rows),
            ":::",
            "",
        ]
    return "\n".join(out)


def module_cards(v: dict, dkey: str) -> str:
    out = ["::: {.module-cards}"]
    for key in day_modules(v, dkey):
        m = v["modules"][key]
        when = module_clock(v, key) or minutes_text(m)
        out += [
            "::: {.module-card}",
            f"[{when}]{{.module-clock}}",
            "",
            f"[Module {module_number(key)}]{{.eyebrow}}",
            "",
            f"**[{m['title']}]({module_link(key, m)})**",
            "",
            "::: {.module-summary}",
            text_or(m.get("summary"), f"summary {TBW}"),
            ":::",
            "",
            "::: {.module-actions}",
            f"[Open the briefing]({module_link(key, m)}){{.btn-quiet}} {colab_buttons(v, key)}",
            ":::",
            ":::",
        ]
    out.append(":::")
    return "\n".join(out)


def run_sheet(v: dict, dkey: str) -> str:
    d = v["days"][dkey]
    segs = plan(v, dkey)
    if not segs:
        return f"{d['label']} has no timetable: the pre-work is done on your own."
    rows = ["| Time | Session | What happens |", "|---|---|---|"]
    for s in segs:
        session, module = segment_cells(v, s)
        if "module" not in s:
            what = ""
        elif s["kind"] == "briefing":
            what = f"{module}: the briefing."
        elif s["kind"] == "lab":
            labs = []
            for e in notebooks_of(v, s["module"]):
                lang = LANG[e["language"]]
                labs.append(
                    f"[{lang} lab]({colab_url(v, e)})"
                    if exists(e)
                    else f"{lang} lab (in preparation)"
                )
            what = (
                f"{module}: {', '.join(labs)}. Stuck on exercise N: open its folded solution,"
                " then `workshop.use_reference(N)` (R: `use_reference(N)`), and go on."
            )
        else:
            decision = text_or(v["modules"][s["module"]].get("decision"), f"decision {TBW}")
            what = f"{module}: debrief on the decision. {decision}"
        rows.append(f"| {clock(s['start'])}–{clock(s['end'])} | {session} | {what} |")
    return "::: {.timetable}\n" + "\n".join(rows) + "\n:::"


# ---- module pages ----------------------------------------------------------------------------


def module_header(v: dict, key: str) -> str:
    m = v["modules"][key]
    d = v["days"][m["day"]]
    n = module_number(key)
    when = part_times(v, key)
    day_text = (
        f"[{d['label']}]({day_link(m['day'])}){{.eyebrow}}"
        if d.get("blocks")
        else (f"[{d['label']}]{{.eyebrow}}")
    )
    meta = f"{day_text} [Module {n}]{{.module-num}} [{minutes_text(m)}]{{.module-time}}"
    if when:
        meta += f" [{when}]{{.module-clock}}"
    langs = [LANG.get(x, x) for x in m.get("language", [])]
    nb_lines = []
    for e in notebooks_of(v, key):
        state = "" if exists(e) else " (in preparation)"
        nb_lines.append(f"{LANG[e['language']]}: `{e['path']}`{state}")
    data = []
    for item in m.get("data") or []:
        if isinstance(item, dict):
            name = item.get("name", "data")
            data.append(f"[{name}]({item['url']})" if item.get("url") else name)
        else:
            data.append(str(item))
    details = [
        ("Day", f"{d['label']} · {d['title']}" + (f" ({module_clock(v, key)})" if when else "")),
        ("Time", minutes_text(m) + (" · optional" if m.get("optional") else "")),
        (
            "Languages",
            ", ".join(langs) + (f". {m['language_why']}" if m.get("language_why") else ""),
        ),
        ("Labs", "<br>".join(nb_lines) if nb_lines else "No lab"),
        ("Data", ", ".join(data) if data else f"*{TBW[0].upper()}{TBW[1:]}.*"),
    ]
    out = [
        "::: {.module-header}",
        "::: {.module-meta}",
        meta,
        ":::",
        "",
        "::: {.module-summary}",
        text_or(m.get("summary"), f"summary {TBW}"),
        ":::",
        "",
        "::: {.module-actions}",
        colab_buttons(v, key) or "[No lab]{.chip}",
        ":::",
        ":::",
        "",
        "::: {.module-decision}",
        f"**The decision.** {text_or(m.get('decision'), f'decision {TBW}')}",
        ":::",
        "",
        "::: {.module-details}",
    ]
    for term, value in details:
        out += [term, f":   {value}", ""]
    out[-1] = ":::"
    out += ["", "::: {.module-outcomes}", "## What you will be able to do", ""]
    objectives = m.get("objectives") or []
    out += [f"- {o}" for o in objectives] if objectives else [f"*Objectives {TBW}.*"]
    outcomes = m.get("outcomes") or []
    if outcomes:
        out += ["", "**You leave with:**", ""] + [f"- {o}" for o in outcomes]
    out += [":::", ""]
    out += prerequisites(v, key)
    return "\n".join(out)


def prerequisites(v: dict, key: str) -> list[str]:
    items = []
    earlier = [k for k, _ in modules(v) if module_number(k) < module_number(key)]
    if earlier:
        prev = earlier[-1]
        pm = v["modules"][prev]
        items.append(
            f"[Module {module_number(prev)} · {pm['title']}]({module_link(prev, pm)}) and its lab."
        )
    kernels = {e["kernel"] for e in notebooks_of(v, key)}
    if "python3" in kernels:
        items.append("A Google account for Colab. The default Python runtime (CPU) is enough.")
    if "ir" in kernels:
        items.append(
            "For the R lab: Colab's R runtime (Runtime > Change runtime type, if Colab does"
            " not pick it from the notebook)."
        )
    items.append("Or the workshop's Docker image, which has every package installed.")
    return ["::: {.prerequisites}", "## Before you start", ""] + [f"- {i}" for i in items] + [":::"]


def alternatives(entries: list[dict]) -> bool:
    """Notebooks with the same name in python/ and r/ are one lab in two languages: a
    participant does one. Different names (Modules 3, 7, 11) are both done in the slot."""
    return len(entries) > 1 and len({Path(e["path"]).stem for e in entries}) == 1


def lab_block(v: dict, key: str) -> str:
    m = v["modules"][key]
    lab = m["minutes"]["lab"]
    entries = notebooks_of(v, key)
    either = alternatives(entries)
    out, totals = [], []
    if either:
        langs = " and ".join(LANG[e["language"]] for e in entries)
        out += [f"The {langs} notebooks are the same lab in two languages: do one.", ""]
    for e in entries:
        lang = LANG[e["language"]]
        found = lab_steps.rows(e)
        title = f"### {lang} lab · `{Path(e['path']).stem}`"
        if not found:
            out += [title, "", f"[{lang} lab in preparation]{{.chip}}", ""]
            continue
        link = f"[Open in Colab]({colab_url(v, e)}){{.btn-colab}}" if exists(e) else ""
        rows = ["| Step | Time |", "|---|---|"]
        for r in found:
            if r["kind"] == "stretch":
                continue
            name = f" · {r['title']}" if r["title"] else ""
            if r["kind"] == "part":
                rows.append(f"| **{r['label']}{name}** | |")
            else:
                time = f"{r['minutes']} min" if r["minutes"] else "—"
                rows.append(f"| {r['label']}{name} | {time} |")
        n = len([r for r in found if r["kind"] == "exercise"])
        minutes = lab_steps.minutes(found)
        totals.append((n, minutes))
        rows.append(f"| **{lang} subtotal: {n} exercises** | **{minutes} min** |")
        out += [title, "", link, "", "::: {.lab-steps}", "\n".join(rows), ":::", ""]
        stretch = next((r for r in found if r["kind"] == "stretch"), None)
        if stretch:
            name = f" · {stretch['title']}" if stretch["title"] else ""
            out += [
                "::: {.challenge}",
                f"**Stretch (optional){name}.** For anyone who finishes early.",
                ":::",
                "",
            ]
    if not totals:
        return "*Lab in preparation.*"
    stub = " Each exercise has a stub to complete, a folded solution and a checkpoint."
    if either or len(entries) == 1:
        n, minutes = max(totals, key=lambda t: t[1])
        out.append(
            f"{n} exercises, {minutes} minutes between them, in a {lab}-minute lab slot.{stub}"
        )
    else:
        n = sum(t[0] for t in totals)
        minutes = sum(t[1] for t in totals)
        missing = len(entries) - len(totals)
        tail = f" ({missing} notebook not written yet)" if missing else ""
        out.append(
            f"Both notebooks together: {n} exercises, {minutes} minutes, in a {lab}-minute lab"
            f" slot{tail}.{stub}"
        )
    return "\n".join(out).strip()


# ---- notebooks, readiness, install times -------------------------------------------------------


def teaching_time(v: dict, entry: dict, records: list[dict]) -> str:
    env = readiness.teaching_env(v, entry["kernel"])
    mine = [
        r
        for r in records
        if r["notebook"] == entry["id"]
        and r["env"] == env
        and readiness.teaching_eligible(v, r)
        and r["status"] == "pass"
    ]
    r = readiness.newest(mine)
    if r is None:
        return "not yet timed on Colab"
    return f"{readiness.duration(r.get('seconds'))} on Colab ({r['date']})"


def notebooks_table(v: dict, records: list[dict]) -> str:
    envs = v["readiness"]["envs"]
    rows = [
        "| Module | Notebook | Language | Runtime | Open | Time on Colab |",
        "|---|---|---|---|---|---|",
    ]
    for e in common.notebooks(v):
        m = v["modules"][e["module"]]
        env = readiness.teaching_env(v, e["kernel"])
        runtime = envs[env]["label"] if env else "—"
        if exists(e):
            badge = f"[![Open in Colab]({BADGE})]({colab_url(v, e)})"
            time = teaching_time(v, e, records)
        else:
            badge, time = "in preparation", "—"
        rows.append(
            f"| [{module_number(e['module'])} · {m['title']}]({module_link(e['module'], m)})"
            f" | `{Path(e['path']).stem}` | {LANG[e['language']]} | {runtime} | {badge} | {time} |"
        )
    note = (
        "Times come from run records of a worked, full-settings run of the whole notebook on"
        " Colab ([readiness](/readiness.qmd)); laptop, Docker and CI times are never shown as"
        " Colab times."
    )
    return "\n".join(rows) + "\n\n" + note


def lane_text(v: dict, lane: dict) -> str:
    if lane["state"] == "documented":
        return "documented, not run"
    if lane["record"] is None:
        return "not run"
    return readiness.describe(lane["record"])


def readiness_summary(report: dict, link: str | None = "/readiness.qmd") -> str:
    s = report["summary"]
    if s["all_ready"] and s["ci_passed"] == s["notebooks"]:
        verdict = "ready to teach"
    elif s["all_ready"]:
        # CI records live on the evidence branch: a checkout without them must not claim more.
        verdict = ("Colab evidence complete; ready to teach once CI passes on the current code"
                   " (the live readiness page counts CI runs)")
    else:
        verdict = "not yet ready to teach"
    when = f"As of {s['as_of']}" if s["as_of"] else "No runs are recorded yet"
    not_written = s["notebooks"] - s["written"]
    parts = [
        f"**{when}: {verdict}.**",
        f"{s['ready']} of {s['notebooks']} notebooks have a current, passing, worked,"
        " full-settings run of the whole notebook on Colab"
        + (f" ({not_written} are not written yet)." if not_written else "."),
        f"{s['elsewhere_passed']} have passed on another machine"
        f" ({s['elsewhere_full']} with full settings), and {s['ci_passed']} on CI.",
    ]
    if link:
        parts.append(f"[What has run, where]({link}).")
    return " ".join(parts)


def readiness_page(v: dict, report: dict) -> str:
    envs = v["readiness"]["envs"]
    rows = ["| Notebook | Ready to teach | Evidence |", "|---|---|---|"]
    for e in report["notebooks"]:
        m = v["modules"][e["module"]]
        ready = "**Yes**" if e["ready"] else f"No: {e['why']}"
        lines = [f"**{envs[k]['label']}:** {lane_text(v, lane)}" for k, lane in e["lanes"].items()]
        if e["learner"] is not None:
            lr = e["learner"]
            verdict = (
                "stopped at checkpoint 1 as designed"
                if lr["status"] == "pass"
                else ("**did not stop as designed**")
            )
            lines.append(f"**Learner mode:** {verdict} ({lr['date']}, {envs[lr['env']]['label']})")
        name = (
            f"`{e['id']}`<br>[Module {module_number(e['module'])}]({module_link(e['module'], m)})"
        )
        rows.append(f"| {name} | {ready} | {'<br>'.join(lines)} |")
    s = report["summary"]
    legend = [
        "## How to read this page {#legend}",
        "",
        "Each evidence line is the newest worked run on that machine, from the run records in"
        f" [`runs/`]({v['repo']['url']}/tree/{v['repo']['ref']}/runs). A newer failure replaces an"
        " older pass. A run is *before the notebook or its deps last changed* when the"
        " notebook's code (content_sha) or the files, pins and ref it depends on (deps_sha) have"
        " changed since; it no longer counts.",
        "",
        "*Ready to teach* needs a passing run on Colab, the runtime the notebook is designed for:"
        " worked (reference solutions bound), the whole notebook, full settings (not QUICK),"
        f" with the current code and deps, at most {s['max_age']} days older than the newest"
        " record on this page. A laptop's, the Docker image's or the CI runner's time does not"
        " predict Colab's. The AWS paths are documented, not run.",
        "",
        "*Learner mode* runs the notebook with nothing written: it must stop at the first"
        " checkpoint with the message that tells a participant how to go on.",
    ]
    return "\n".join(
        [
            readiness_summary(report, link=None),
            "",
            "::: {.readiness-table}",
            "\n".join(rows),
            ":::",
            "",
            *legend,
        ]
    )


def install_times(v: dict, records: list[dict]) -> str:
    envs = v["readiness"]["envs"]
    rows = ["| Runtime | Notebook | Install and setup | Measured |", "|---|---|---|---|"]
    for key, env in envs.items():
        if not env.get("teaching"):
            continue
        measured = {}
        for r in records:
            if (
                r["env"] == key
                and r.get("install_seconds") is not None
                and r.get("runtime")
                in (
                    "colab",
                    "sagemaker",
                )
            ):
                best = measured.get(r["notebook"])
                if best is None or (r["date"], r.get("file", "")) > (
                    best["date"],
                    best.get("file", ""),
                ):
                    measured[r["notebook"]] = r
        if not measured:
            rows.append(f"| {env['label']} | — | not yet measured | — |")
        for nb_id, r in sorted(measured.items()):
            rows.append(
                f"| {env['label']} | `{nb_id}` | {readiness.duration(r['install_seconds'])}"
                f" | {r['date']} |"
            )
    note = (
        "Measured by each notebook's install cell on a fresh runtime and read from its run"
        " record. On your own machine or in the workshop's Docker image nothing is installed."
    )
    return "\n".join(rows) + "\n\n" + note


def sidebar(v: dict) -> str:
    sections = []
    for dkey, d in days(v):
        keys = day_modules(v, dkey)
        if not keys:
            continue
        sections.append(
            {
                "section": f"{d['label']} · {d['title']}",
                "contents": [
                    {
                        "href": f"modules/{v['modules'][k]['slug']}.qmd",
                        "text": f"{module_number(k)} · {v['modules'][k]['title']}",
                    }
                    for k in keys
                ],
            }
        )
    tree = {"website": {"sidebar": [{"id": "modules", "title": "Modules", "contents": sections}]}}
    head = "# GENERATED by scripts/gen_tables.py from _variables.yml. Do not edit by hand.\n"
    return head + yaml.safe_dump(tree, sort_keys=False, allow_unicode=True, width=1000)


# ---- VERSIONS.md ---------------------------------------------------------------------------

KEY_PINS = (
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "statsmodels",
    "lightgbm",
    "pymc",
    "pytensor",
    "arviz",
    "numba",
    "duckdb",
    "pyarrow",
    "matplotlib",
    "ipykernel",
    "ipython",
    "nbclient",
    "jupytext",
    "pyyaml",
    "pytest",
    "ruff",
)


def versions(v: dict) -> str:
    env = v["environment"]
    pins = common.requirements_pins()
    out = [
        "# Versions",
        "",
        "What the labs run, and the docs or source each pin was checked against. Python pins are"
        " compiled into `environment/requirements.txt` with Colab's own package versions as"
        " constraints; R packages come from a dated Posit Public Package Manager snapshot.",
        "",
        "## Runtimes",
        "",
        "| | Version |",
        "|---|---|",
        f"| Python | {env['python']} |",
        f"| R | {env['r']} |",
        f"| Quarto | {env['quarto']} |",
        f"| R package snapshot | [{env['p3m_snapshot']}]({env['p3m_url']}) |",
        f"| Colab | {env['colab_runtime']} ([backend-info]({env['colab_backend_info']})) |",
        "",
        "## Python packages the labs install",
        "",
        "| Package | Version | Checked | Against | Docs |",
        "|---|---|---|---|---|",
    ]
    for name, p in (v.get("packages") or {}).items():
        out.append(
            f"| {name} | {p['version']} | {p.get('checked', '—')} | {p.get('against', '—')}"
            f" | {p.get('docs', '—')} |"
        )
    out += ["", "## R packages", "", "| Package | Version | Docs |", "|---|---|---|"]
    for name, p in (v.get("r_packages") or {}).items():
        out.append(f"| {name} | {p.get('version', '—')} | {p.get('docs', '—')} |")
    out += [
        "",
        "## R packages from GitHub (pinned archives)",
        "",
        "| Package | Repository | Commit | Licence |",
        "|---|---|---|---|",
    ]
    for name, p in (v.get("github_packages") or {}).items():
        out.append(
            f"| {name} | [{p['repo']}](https://github.com/{p['repo']}) | `{p['sha']}`"
            f" | {p.get('license', '—')} |"
        )
    out += [
        "",
        "## Other key Python pins",
        "",
        f"`environment/requirements.txt` pins {len(pins)} packages; these matter most:",
        "",
        "| Package | Version |",
        "|---|---|",
    ]
    out += [f"| {n} | {pins[n]} |" for n in KEY_PINS if n in pins]
    return "\n".join(out)


# ---- writing -------------------------------------------------------------------------------


def outputs(v: dict) -> dict[Path, str]:
    records = run_records.load_valid(v)
    report = readiness.build(v, records, readiness.newest_date(records))
    var_notice = NOTICE.format(src="_variables.yml")
    lab_notice = NOTICE.format(src="_variables.yml and the headings of labs/src")
    runs_notice = NOTICE.format(src="_variables.yml and the run records in runs/")
    files = {
        INCLUDES / "facts.md": (var_notice, facts(v)),
        INCLUDES / "days.md": (var_notice, days_cards(v)),
        INCLUDES / "path.md": (var_notice, path(v)),
        INCLUDES / "schedule.md": (var_notice, schedule(v)),
        INCLUDES / "notebooks.md": (runs_notice, notebooks_table(v, records)),
        INCLUDES / "readiness.md": (runs_notice, readiness_page(v, report)),
        INCLUDES / "readiness-summary.md": (runs_notice, readiness_summary(report)),
        INCLUDES / "install-times.md": (runs_notice, install_times(v, records)),
        ROOT / "environment" / "VERSIONS.md": (
            NOTICE.format(src="environment/requirements.txt and _variables.yml"),
            versions(v),
        ),
    }
    for dkey, _ in days(v):
        n = day_number(dkey)
        files[INCLUDES / f"day-{n}.md"] = (var_notice, module_cards(v, dkey))
        files[INCLUDES / f"run-{n}.md"] = (var_notice, run_sheet(v, dkey))
    for key, _ in modules(v):
        n = module_number(key)
        files[INCLUDES / f"module-{n:02d}.md"] = (var_notice, module_header(v, key))
        files[INCLUDES / f"lab-{n:02d}.md"] = (lab_notice, lab_block(v, key))
    out = {p: f"{notice}\n\n{body.rstrip()}\n" for p, (notice, body) in files.items()}
    out[INCLUDES / "sidebar.yml"] = sidebar(v)
    readme = ROOT / "README.md"
    if readme.exists():
        site = v["repo"]["site"].rstrip("/")
        status = "> " + readiness_summary(report, link=f"{site}/readiness.html")
        out[readme] = replace_region(readme.read_text(encoding="utf-8"), "status", status)
    return out


def replace_region(text: str, name: str, body: str) -> str:
    begin, end = f"<!-- BEGIN {name} -->", f"<!-- END {name} -->"
    if begin not in text or end not in text:
        return text
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{begin}\n{body.rstrip()}\n{end}{tail}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if anything would change")
    args = parser.parse_args(argv)
    v = common.load_variables()
    drift = []
    for out, text in outputs(v).items():
        current = out.read_text(encoding="utf-8") if out.exists() else None
        if current == text:
            continue
        drift.append(out.relative_to(ROOT).as_posix())
        if not args.check:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(text, encoding="utf-8")
    if args.check and drift:
        print("Generated files are out of date (run python scripts/gen_tables.py):")
        print("\n".join(f"  {p}" for p in drift))
        return 1
    if not args.check:
        print(f"{len(drift)} file(s) written" if drift else "Nothing to change")
    return 0


if __name__ == "__main__":
    sys.exit(main())
